site_name: RxDocs - Gestion des couleurs
site_url: https://docs.rainboxlab.org/couleurs/
repo_url: https://github.com/Rainbox-dev/RxDocs/
edit_uri: edit/master/src-couleurs/docs/
site_description: The RxDocuments - Gestion des couleurs dans la production audiovisuelle.
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2021 <a href="https://rainboxlagb.org">Rainbox Laboratory</a>, <a href="https://duduf.com">Nicolas Dufresne</a> and contributors'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - attr_list
    - toc:
        permalink: true
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/couleurs
dev_addr: '127.0.0.1:8001'
nav:
    - Introduction: index.md
    - Théorie:
        - A - Qu'est ce que la couleur ?: A-definition.md
        - B - Petit inventaire et classification des couleurs: B-inventaire.md
        - C - Perception des couleurs: C-perception.md
        - D - Reproduction des couleurs : D-reproduction.md
        - E - Retour sur les blancs, température: E-temperature.md
        - F - Représentation objective: F-representation.md
        - G - Du réel au numérique: G-numerisation.md
        - H - Qu'est ce qu'un espace colo ?: H-espace-colo.md
        - I - Liste d'espaces colorimétriques: I-liste-espaces.md
        - J - Liste des paramètres d'espaces colorimétriques: J-liste-params.md 
        - K - Format des pixels: K-pix-format.md
        - L - Courbes de transfert, espace linéaire et gamma: L-transfert.md
        - M - Les LUTs: M-LUT.md
        - N - OCIO, ACES: N-ocio.md
        - O - Épreuvage (Soft-Proofing): O-epreuve.md
    - Pratique:
        - A - Choisir ses espaces colorimétriques et formats: 2A-pratique.md
        - B - Formats de fichiers: 2B-standards.md
        - C - Calibration des écrans: 2C-calibration.md
        - D - Préparer la chaîne de fabrication: 2D-preparer.md
        - E - Concevoir une chaîne de fabrication avec OCIO: 2E-ocio.md
        - F - Adobe After Effects: 2F-ae.md
        - G - Adobe Media Encoder: .
        - H - Adobe Premiere: .
        - I - Blender: 2I-blender.md
        - J - Darktable: .
        - K - DuME: .
        - L - Krita: 2L-krita.md
    - Annexes:
        - En bref, le résumé pour ne pas se tromper: ZZ-bref.md
        - Erreurs et résolution des problèmes: ZZ-erreurs.md
        - Glossaire: ZZ-vocabulaire.md
        - Dictionnaire français - anglais: ZZ-english.md
        - Téléchargements: ZZ-download.md
    - ...:
        - Tous les documents RxLab: http://docs.rainboxlab.org
        - Contribuer à la rédaction: http://docs.rainboxlab.org/contribute.html
        - Contact: https://rainboxlab.org/about/contact/
        - Donate: https://rainboxlab.org/about/donate/

