site_name: RxDocs - Gestion des couleurs
site_url: https://docs.rainboxlab.org/couleurs/
repo_url: https://github.com/Rainbox-dev/RxDocs/
edit_uri: edit/master/src-couleurs/docs/
site_description: The RxDocuments - Gestion des couleurs dans la production audiovisuelle.
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2021 <a href="https://rainboxlagb.org">Rainbox Laboratory</a>, <a href="https://duduf.com">Nicolas Dufresne</a> and contributors'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - attr_list
    - toc:
        permalink: true
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
site_dir: ../docs/couleurs
dev_addr: '127.0.0.1:8001'
nav:
    - Gestion des couleurs:
        - Introduction: index.md
        - A - Définition: 01-definition.md
        - B - Perception des couleurs: 02-perception.md
        - C - Le blanc, le pourpre, et autres mélanges: 08-blanc.md
        - D - Représentation objective: 03-representation.md
        - E - Du réel au numérique: 04-numerisation.md
        - F - Qu'est ce qu'un espace colo ?: 05-espace-colo.md
        - G - Liste d'espaces colorimétriques: 06-liste-espaces.md
        - H - Liste des paramètres d'espaces colorimétriques: 07-liste-params.md 
        - I - RGB et YUV: 09-rgb-yuv.md
        - J - YUV 444, 422, 421, 420...: 10-444.md
        - Glossaire: ZZ-vocabulaire.md
    - Tous les documents RxLab: http://docs.rainboxlab.org
    - Contribuer à la rédaction: http://docs.rainboxlab.org/contribute.html
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/

