site_name: RxDocs - Free Software
site_url: https://docs.rainboxlab.org/freesoftware
repo_url: https://github.com/Rainbox-dev/RxDocs/
edit_uri: edit/master/src-docs/docs/freesoftware/
site_description: The RxDocuments - The 100% Free software pipeline
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2021 <a href="https://rainboxlagb.org">Rainbox Laboratory</a>, <a href="https://duduf.com">Nicolas Dufresne</a> and contributors'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - attr_list
    - toc:
        permalink: true
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
site_dir: ../docs/freesoftware
dev_addr: '127.0.0.1:8001'
nav:
    - The 100% Free pipeline:
        - Introduction: index.md
    - All the RxLab documents: ../index.html
    - Contribute to the doc: ../contribute.html
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/

