site_name: RxDocs Documentation
site_url: https://docs.rxlab.guide
repo_url: https://github.com/RxLaboratory/RxDocs/
edit_uri: edit/master/src-docs/docs/
site_description: The RxDocs comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2021 <a href="https://rainboxlagb.org">Rainbox Laboratory</a>, <a href="https://duduf.com">Nicolas Dufresne</a> and contributors'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - RxDocs: index.md
    - How to edit documentation: howto.md
    - Changelog: changelog.md
    - Credits: credits.md
    - License:
        - GNU GPLv3: licenses/gnu-gpl.md
        - Documentation license: licenses/gfdl.md
