site_name: RxDocs
site_url: https://docs.rainboxlab.org
repo_url: https://github.com/Rainbox-dev/RxDocs/
edit_uri: edit/master/src-docs/docs/
site_description: The RxDocuments - RxLab Documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2021 <a href="https://rainboxlagb.org">Rainbox Laboratory</a>, <a href="https://duduf.com">Nicolas Dufresne</a> and contributors'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - attr_list
    - toc:
        permalink: true
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - RxDocs: index.md
    - Comprehensive guides: guides.md
    - (en) openEXR compression methods:
        - Introduction: exr/index.md
        - Summary: exr/summary.md
        - Luminance/Chroma option: exr/luma-chroma.md
        - Formats you don’t know you already know: exr/formats-you-know.md
        - Summary by usage and type of image: exr/usage.md
        - Details: exr/details.md
        - A note about frame sequences: exr/sequences.md
    - (fr) Méthodes de compression openEXR:
        - Introduction: exr-fr/index.md
    - (en) Colors and Color Management:
        - Introduction: colors/index.md
    - (fr) Couleurs et gestion des couleurs:
        - Introduction: couleurs/index.md
        - Définition: couleurs/01-definition.md
        - Perception des couleurs: couleurs/02-perception.md
        - Représentation objective: couleurs/03-representation.md
        - Du réel au numérique: couleurs/04-numerisation.md
    - (en) The 100% free pipeline:
        - Introduction: freesoftware/index.md
    - (en) The Green Guide to transccoding:
        - Introduction: green/index.md
        - Intermediary formats: green/intermediary.md
        - Edit and color grading: green/grading.md
        - Final delivery: green/final.md
    - Contribute to the doc: contribute.md
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/

